# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-07 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetNum', models.CharField(default='', max_length=128, verbose_name='资产编号')),
                ('assetType', models.CharField(max_length=20, verbose_name='类型名称')),
                ('brand', models.CharField(blank=True, max_length=20, null=True, verbose_name='品牌')),
                ('model', models.CharField(default='', max_length=128, verbose_name='型号')),
                ('service_num', models.CharField(default='', max_length=128, verbose_name='SN码')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='价格')),
                ('status', models.CharField(choices=[('0', '闲置'), ('1', '在用'), ('2', '维修'), ('3', '报废')], default='1', max_length=20, verbose_name='资产状态')),
                ('customer', models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='供应商')),
                ('department', models.CharField(blank=True, max_length=80, verbose_name='使用部门')),
                ('owner', models.CharField(blank=True, max_length=80, verbose_name='使用人')),
                ('production_time', models.DateTimeField(verbose_name='生产日期')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('desc', models.TextField(blank=True, default='', null=True, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '资产管理',
                'verbose_name_plural': '资产管理',
            },
        ),
    ]
