# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-07 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_remove_asset_assettype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='类型名称', max_length=30, verbose_name='类型名称')),
            ],
            options={
                'verbose_name': '类型名称',
            },
        ),
    ]
