# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-07 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_assettype'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assetType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.AssetType', verbose_name='类型名称'),
        ),
    ]
