# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-07 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180907_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='image/default.jpg', null=True, upload_to='image/%Y/%m'),
        ),
    ]
